version: '3'
services:
    mysql-container:
        image: mysql:5.7.21
        volumes:
            - mysql-volume:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    web-container:
        depends_on:
            - mysql-container
        networks:
            - default
        build: .
        ports:
            - "8080:80"
        volumes:
            - ./camagru:/var/www/html/

        links:
            - mysql-container
            - maildev:maildev
    phpmyadmin-container:
        depends_on:
            - mysql-container
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        links:
            - mysql-container:db
    maildev:
        image: djfarrelly/maildev
        ports:
            - "8082:80"
            - "1025:25"
volumes:
    mysql-volume:
