#docker build -f /path/to/a/Dockerfile
#You use the -f flag with docker build to point to a Dockerfile anywhere in your file system.
FROM debian
RUN apt-get -y update && apt-get -y dist-upgrade && apt-get install -y 	vim \
																		gcc \
																		make \
																		git-all
